### ISSUE TITLE
TypeError: (0 , _uncontrollable.default) is not a function

### ISSUE THREAD

**Issue by putvande** [react-bootstrap/react-overlays#300]
About an hour ago, [uncontrollable](https://github.com/jquense/uncontrollable) has released a new version: https://github.com/jquense/uncontrollable/releases 

This release now requires you to import the package as `import { uncontrollable } from 'uncontrollable'`,instead of `import uncontrollable from 'uncontrollable'`(currently in your codebase)

This change breaks my code when using the React-overlays 1.2.0 plugin.

I get the following error message:

```
/src/node_modules/react-overlays/Dropdown.js:305
| var UncontrolledDropdown = (0, _uncontrollable.default)(Dropdown, {
|                                                        ^
| 
| TypeError: (0 , _uncontrollable.default) is not a function
|     at Object.<anonymous> (/src/node_modules/react-overlays/Dropdown.js:305:56)
|     at Module._compile (internal/modules/cjs/loader.js:701:30)
|     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
|     at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-register/lib/node.js:152:7)
|     at Module.load (internal/modules/cjs/loader.js:600:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
|     at Module.require (internal/modules/cjs/loader.js:637:17)
|     at require (internal/modules/cjs/helpers.js:22:18)
|     at Object.<anonymous> (/src/node_modules/react-overlays/index.js:29:40)
|     at Module._compile (internal/modules/cjs/loader.js:701:30)
|     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
|     at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-register/lib/node.js:152:7)
|     at Module.load (internal/modules/cjs/loader.js:600:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
|     at Module.require (internal/modules/cjs/loader.js:637:17)
|     at require (internal/modules/cjs/helpers.js:22:18)
|     at Object.<anonymous> (/src/client/src/themeBlueprint/src/AvailabilityContainer.jsx:10:1)
|     at Module._compile (internal/modules/cjs/loader.js:701:30)
|     at loader (/src/node_modules/babel-register/lib/node.js:144:5)
|     at Object.require.extensions.(anonymous function) [as .jsx] (/src/node_modules/babel-register/lib/node.js:154:7)
|     at Module.load (internal/modules/cjs/loader.js:600:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
|     at Module.require (internal/modules/cjs/loader.js:637:17)
|     at require (internal/modules/cjs/helpers.js:22:18)
|     at Object.<anonymous> (/src/test/client/src/themeBlueprint/src/AvailabilityContainer.test.jsx:2:1)
|     at Module._compile (internal/modules/cjs/loader.js:701:30)
|     at loader (/src/node_modules/babel-register/lib/node.js:144:5)
|     at Object.require.extensions.(anonymous function) [as .jsx] (/src/node_modules/babel-register/lib/node.js:154:7)
|     at Module.load (internal/modules/cjs/loader.js:600:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
|     at Module.require (internal/modules/cjs/loader.js:637:17)
|     at require (internal/modules/cjs/helpers.js:22:18)
|     at /src/node_modules/mocha/lib/mocha.js:250:27
|     at Array.forEach (<anonymous>)
|     at Mocha.loadFiles (/src/node_modules/mocha/lib/mocha.js:247:14)
|     at Mocha.run (/src/node_modules/mocha/lib/mocha.js:576:10)
|     at Object.<anonymous> (/src/node_modules/mocha/bin/_mocha:637:18)
|     at Module._compile (internal/modules/cjs/loader.js:701:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
|     at Module.load (internal/modules/cjs/loader.js:600:32)
|     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
|     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
|     at startup (internal/bootstrap/node.js:283:19)
|     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

**Comment by jquense** [comment]
should be fixed upstream now, try cleaning and reinstalling

**Comment by putvande** [comment]
Thanks @jquense. Working now.

**Comment by MarkEmerson** [comment]
**packages:**
react-dom: 16.8.6
react:16.8.6
react-overlays:1.2.0

**still getting this error:** 

browser source:
Uncaught TypeError: (0 , _uncontrollable.default) is not a function

var UncontrolledDropdown = (0, _uncontrollable.default)(Dropdown, {
  show: 'onToggle'
});

browsewr console output:
Uncaught TypeError: (0 , _uncontrollable.default) is not a function
    at Object../node_modules/react-bootstrap/node_modules/react-overlays/Dropdown.js (Dropdown.js:305)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object../node_modules/react-bootstrap/es/Dropdown.js (app.5aa110fbdd7b2189a480.js:105655)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object../node_modules/react-bootstrap/es/index.js (app.5aa110fbdd7b2189a480.js:110277)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object.<anonymous> (TooltipWrapper.jsx:2)
client?843a:38 [WDS] Hot Module Replacement enabled.

we do not directly use the uncontrolled component, it is being used by react-overlays in the Dropdown component.

anything i may be missing?

**Comment by 07harish** [comment]
I resolved this problem, Usually we see this error because we are importing files in wrong way.

Here is how I imported and solved it: 
Before:
 import { Row, Col } from 'react-bootstrap'; 
This didn't work

After::
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

Worked!
