### ISSUE TITLE
Show transition is not being correctly displayed

### ISSUE THREAD

**Issue by PedroFonseca** [react-bootstrap/react-overlays#70]
So i have a component that returns this jsx:
&lt;Transition
    transitionAppear
    unmountOnExit
    in={this.props.visible}
    timeout={this.props.timeout}
    className={classNames(this.props.className, this.props.transitionName) }
    enteringClassName="entering"
    enteredClassName="entered"
    exitingClassName="exiting"
    &gt;
    &lt;div&gt;my dom&lt;/div&gt;
&lt;/Transition&gt;

I'd expect that i could then simply change the props.visible to make my dom show/hide using the transition of my choice. The transition is correctly displayed when hiding the component (setting props.visible to false) but when showing the component it does not show a transition. 
It looks to me that it renders the entering class to fast after the render of the component and react makes both updates on the DOM at the same time, and that in turn will make the transition not work.

I've played a little bit with the source code and found out that if i change the Transition.prototype.componentDidUpdate method to delay the performEnter just a bit (5 milliseconds worked for me) then it all works fine. I've tested it both in firefox and chrome.
Is this a real issue or am i doing something wrong?

Thanks in advance,
Pedro Fonseca

PS: This is the change i made to the componentDidUpdate method:

Transition.prototype.componentDidUpdate = function componentDidUpdate() {
&nbsp;&nbsp;if (this.props.unmountOnExit && this.state.status === EXITED) {
&nbsp;&nbsp;&nbsp;&nbsp;// EXITED is always a transitional state to either ENTERING or UNMOUNTED
&nbsp;&nbsp;&nbsp;&nbsp;// when using unmountOnExit.
&nbsp;&nbsp;&nbsp;&nbsp;if (this.props['in']) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var that = this;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(function () { that.performEnter(that.props); }, 5);
&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.setState({ status: UNMOUNTED });
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
};

**Comment by PedroFonseca** [comment]
I've seen the open PR (#31) from Marty for this and i do think this should be fixed.
In the meanwhile, i found out a way around this issue. For anyone also having this issue, this is what worked for me.
Since in my transition i don't need the entering or exiting stages, i setup my css transition like this:

.transition-fade {
&nbsp;&nbsp;&nbsp;&nbsp;opacity: 0.3;
&nbsp;&nbsp;&nbsp;&nbsp;filter: alpha(opacity=30);
&nbsp;&nbsp;&nbsp;&nbsp;transition: opacity 500ms ease-in;
}
.transition-fade.in {
&nbsp;&nbsp;&nbsp;&nbsp;opacity: 1;
&nbsp;&nbsp;&nbsp;&nbsp;filter: alpha(opacity=100);
}

And then i use this jsx to render it
&lt;Transition
&nbsp;&nbsp;transitionAppear
&nbsp;&nbsp;unmountOnExit
&nbsp;&nbsp;in={this.props.visible}
&nbsp;&nbsp;timeout={this.props.visible ? 0 : this.props.timeout}
&nbsp;&nbsp;className={classNames(this.props.className, this.props.transitionName) }
&nbsp;&nbsp;enteredClassName="in"
&nbsp;&nbsp;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{this.props.children}
&lt;/Transition&gt;

**Comment by taion** [comment]
As with #31, I think this was fixed in #60.

**Comment by sharq1** [comment]
@taion it's still broken for me and I am forced to use above hack :(
